---
  - name: iptables-persistent
    package:
      name: iptables-persistent
      state: present

  - name: Enable and start netfilter-persistent
    service:
      name: netfilter-persistent
      enabled: yes
      state: started

  - name: Drop invalid packets
    iptables_raw:
      name: new_nonsyn_block
      weight: 10
      table: mangle
      rules: |
        ### Drop invalid packets ###
        -A PREROUTING -m conntrack --ctstate INVALID -j DROP
      state: present

  - name: Drop TCP packets that are new and are not SYN
    iptables_raw:
      name: new_nonsyn_block
      weight: 10
      table: mangle
      rules: |
        ### Drop TCP packets that are new and are not SYN ###
        -A PREROUTING -p tcp ! --syn -m conntrack --ctstate NEW -j DROP
      state: present

  - name: Drop SYN packets with suspicious MSS value
    iptables_raw:
      name: suspicious_syn_block
      weight: 10
      table: mangle
      rules: |
        ### Drop SYN packets with suspicious MSS value ###
        -A PREROUTING -p tcp -m conntrack --ctstate NEW -m tcpmss ! --mss 536:65535 -j DROP
      state: present

  - name: Block packets with bogus TCP flags
    iptables_raw:
      name: bogus_block
      weight: 10
      table: mangle
      rules: |
        ### Drop TCP packets that are new and are not SYN ###
        -A PREROUTING -p tcp ! --syn -m conntrack --ctstate NEW -j DROP
        ### Drop SYN packets with suspicious MSS value ###
        -A PREROUTING -p tcp -m conntrack --ctstate NEW -m tcpmss ! --mss 536:65535 -j DROP
      state: present

  - name: Block packets with bogus TCP flags
    iptables_raw:
      name: bogus_block
      weight: 10
      table: mangle
      rules: |
        ### Block packets with bogus TCP flags ###
        -A PREROUTING -p tcp --tcp-flags FIN,SYN FIN,SYN -j DROP
        -A PREROUTING -p tcp --tcp-flags SYN,RST SYN,RST -j DROP
        -A PREROUTING -p tcp --tcp-flags FIN,RST FIN,RST -j DROP
        -A PREROUTING -p tcp --tcp-flags FIN,ACK FIN -j DROP
        -A PREROUTING -p tcp --tcp-flags ACK,URG URG -j DROP
        -A PREROUTING -p tcp --tcp-flags ACK,PSH PSH -j DROP
        -A PREROUTING -p tcp --tcp-flags ALL NONE -j DROP
      state: present

  - name: Ping Flood,PoD
    iptables_raw:
      name: icmp_block
      weight: 10
      table: mangle
      rules: |
        ### Drop ICMP (you usually don't need this protocol) ###
        -A PREROUTING -p icmp -j DROP
      state: present

  - name: UDP fragmentation flood
    iptables_raw:
      name: udp_block_fragmented
      weight: 10
      table: mangle
      rules: |
        ### Drop fragments in all chains ###
        -A PREROUTING -f -j DROP
      state: present

  - name: SSH brute-force protection
    iptables_raw:
      name: ssh_brtueforece_block
      weight: 10
      table: filter
      rules: |
        ### SSH brute-force protection ###
        -A INPUT -p tcp --dport 1983 -m conntrack --ctstate NEW -m recent --set
        -A INPUT -p tcp --dport 1983 -m conntrack --ctstate NEW -m recent --update --seconds 60 --hitcount 10 -j DROP
      state: present

  - name: Protection against port scanning
    iptables_raw:
      name: port_scanning_block
      weight: 10
      table: filter
      rules: |
        ### Protection against port scanning ###
        -N port-scanning
        -A port-scanning -p tcp --tcp-flags SYN,ACK,FIN,RST RST -m limit --limit 1/s --limit-burst 2 -j RETURN
        -A port-scanning -j DROP
      state: present




