---
  - name: Check cluster has initialized
    stat:
      path: /root/.kube/config
    register: kube_config

  - name: Initialize cluster
    when: not kube_config.stat.exists
    block:

      - name: Create kubeadm-config.yaml
        template:
          src: kubeadm-config.j2
          dest: /root/kubeadm-config.yaml

      - name: Initialize the Kubernetes cluster using kubeadm
        command: kubeadm init --config=/root/kubeadm-config.yaml --upload-certs
        ignore_errors: yes

      - name: Setup kubeconfig for vagrant user
        command: "{{ item }}"
        with_items:
         - mkdir -p /root/.kube
         - cp -i /etc/kubernetes/admin.conf /root/.kube/config

      - name: Install calico pod network
        command: kubectl create -f https://docs.projectcalico.org/manifests/calico.yaml

      - name: Finetune cluster
        command: "{{ item }}"
        with_items:
          - kubectl taint nodes --all node-role.kubernetes.io/control-plane-
          - kubectl taint nodes --all node-role.kubernetes.io/master--
        ignore_errors: yes
