apiVersion: v1
kind: Service
metadata:
  name: nfs-server
  labels:
    app: nfs-server-app
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    app: nfs-server-app


