apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server-depl
  labels:
    app: nfs-server-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-server-app
  template:
    metadata:
      labels:
        app: nfs-server-app
    spec:
      volumes:
        - name: nfs-server-storage
          persistentVolumeClaim:
            claimName: nfs-server-pvc
      initContainers:
      - name: nfs-server-init
        image: busybox:1.28
        command: ['sh', '-c', "mkdir -p /exports/www;"]
        volumeMounts:
          - mountPath: "/exports"
            name: nfs-server-storage
      containers:
      - name: nfs-server-container
        image: k8s.gcr.io/volume-nfs:0.8
        securityContext:
          privileged: true
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        volumeMounts:
          - mountPath: "/exports"
            name: nfs-server-storage

